### ISSUE TITLE
Example App occurred Unhandled exception: type 'Future<dynamic>' is not a subtype of type 'Future<String>'

### ISSUE THREAD

**Issue by nakasho-dev** [aloisdeniel/flutter_plugin_appcenter#1]
I tried to run the example. But Build Error.
I was build success when I replaced 'AppcenterAnalytics' to 'AppCenterAnalytics'  in main.dart

But error Occurred.

`E/flutter ( 9825): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9825): type 'Future<dynamic>' is not a subtype of type 'Future<String>' where
E/flutter ( 9825):   Future is from dart:async
E/flutter ( 9825):   Future is from dart:async
E/flutter ( 9825):   String is from dart:core
E/flutter ( 9825): 
E/flutter ( 9825): #0      AppCenter.start (package:appcenter/appcenter.dart:14:86)
E/flutter ( 9825): #1      _MyAppState.initPlatformState (file:///Users/nakasho/study/flutter_plugin_appcenter/example/lib/main.dart:35:21)
E/flutter ( 9825): <asynchronous suspension>
E/flutter ( 9825): #2      _MyAppState.initState (file:///Users/nakasho/study/flutter_plugin_appcenter/example/lib/main.dart:30:5)
E/flutter ( 9825): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
E/flutter ( 9825): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter ( 9825): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 9825): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter ( 9825): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
E/flutter ( 9825): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
E/flutter ( 9825): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
E/flutter ( 9825): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
E/flutter ( 9825): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
E/flutter ( 9825): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
E/flutter ( 9825): #13     runApp (package:flutter/src/widgets/binding.dart:704:7)
E/flutter ( 9825): #14     main (file:///Users/nakasho/study/flutter_plugin_appcenter/example/lib/main.dart:9:16)
E/flutter ( 9825): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter ( 9825): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
W/AppCenter( 9825): App Center may only be configured once.
`
my flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

**Comment by farcasclaudiu** [comment]
+1
