### ISSUE TITLE
AppSecretDenied - wrong format ? 

### ISSUE THREAD

**Issue by Beautylivery** [aloisdeniel/flutter_plugin_appcenter#24]
Hi i build in the pub.dev AppCenter Lib for Flutter and tun into this AppSecretDenied error which seems like my secret is not correct. 

Comparing it with other reference secrets it seems mine has no dahsed "-" in it and seems a little longer.
Personally i want to believe that AppCenter may have changed it ? Or is it possible i am creating my appSecret at the wrong place ?

Setting > AppAPI Tokens.

Resulting error below

```
E/AppCenter(32626): Sending logs groupName=group_core id=******* failed
E/AppCenter(32626): com.microsoft.appcenter.http.HttpException: 401 - {"status":"AppSecretDenied","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"*******"}
E/AppCenter(32626): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:265)
E/AppCenter(32626): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
E/AppCenter(32626): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
E/AppCenter(32626): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AppCenter(32626): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AppCenter(32626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AppCenter(32626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AppCenter(32626): 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by Beautylivery** [comment]
Ok seems i found the issue ... i just expected it is the token... but there is actually a description with the right formatted style that i was supposed to copy...
